// components/RatingStars.vue
<template>
  <div class="flex">
    <Star
      v-for="i in fullStars"
      :key="`full-${i}`"
      :class="[starSizes[size], 'text-yellow-400 fill-current']"
    />
    <StarHalf
      v-if="hasHalfStar"
      :class="[starSizes[size], 'text-yellow-400 fill-current']"
    />
    <Star
      v-for="i in emptyStars"
      :key="`empty-${i}`"
      :class="[starSizes[size], 'text-gray-300']"
    />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { Star, StarHalf } from 'lucide-vue-next'

interface Props {
  rating: number
  size?: 'sm' | 'md' | 'lg'
}

const props = withDefaults(defineProps<Props>(), {
  size: 'md'
})

const starSizes = {
  sm: 'h-4 w-4',
  md: 'h-5 w-5',
  lg: 'h-6 w-6'
}

const fullStars = computed(() => Math.floor(props.rating))
const hasHalfStar = computed(() => props.rating % 1 >= 0.5)
const emptyStars = computed(() => 5 - Math.ceil(props.rating))
</script>

// src/components/RatingStars.tsx
import React from 'react';
import { Star, StarHalf } from 'lucide-react';

interface RatingStarsProps {
  rating: number;
  size?: 'sm' | 'md' | 'lg';
}

const RatingStars = ({ rating, size = 'md' }: RatingStarsProps) => {
  const fullStars = Math.floor(rating);
  const hasHalfStar = rating % 1 >= 0.5;
  const starSizes = {
    sm: 'h-4 w-4',
    md: 'h-5 w-5',
    lg: 'h-6 w-6'
  };

  return (
    <div className="flex">
      {[...Array(fullStars)].map((_, i) => (
        <Star
          key={`full-${i}`}
          className={`${starSizes[size]} text-yellow-400 fill-current`}
        />
      ))}
      {hasHalfStar && (
        <StarHalf className={`${starSizes[size]} text-yellow-400 fill-current`} />
      )}
      {[...Array(5 - Math.ceil(rating))].map((_, i) => (
        <Star
          key={`empty-${i}`}
          className={`${starSizes[size]} text-gray-300`}
        />
      ))}
    </div>
  );
};

export default RatingStars;
